### PR TITLE
Updating and component-friendly spread attributes

### PR DESCRIPTION
**Pull request by Rich-Harris**
This builds on https://github.com/sveltejs/svelte/pull/280 to add support for `<Component {{options}}/>`, and to update the DOM when the object changes (previously spread attributes only applied to the initial render).

There's one failing SSR test which I didn't want to fix until https://github.com/sveltejs/svelte/pull/281 is merged in order to avoid dealing with merge conflicts

### CODE REVIEW

**Comment by PaulBGD** [comment]
Ah, I just noticed that you fixed a bug I wasn't aware of. I forgot to update spread attributes.

**Comment by Rich-Harris** [comment]
~~bear with me a few minutes and I'll update this PR to fix that failing test~~

**Comment by PaulBGD** [comment]
Is that everything?

**Comment by Rich-Harris** [comment]
yep

**Pull request merged**
